# Vị trí sảnh chờ
war-location:
  world: "newbox"
  x: 70.525
  y: 173
  z: 83.487
  
lobby-location:
  world: "newbox"
  x: 70.525
  y: 173
  z: 83.487

map-center:
  world: "newbox"
  x: 70.525
  y: 173
  z: 83.487
# Thời gian miễn nhiễm sát thương khi bắt đầu (giây)
invincibility-duration: 60
# Số người chơi tối thiểu để bắt đầu
min-players: 1